# Generated by Django 5.1.4 on 2025-01-16 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasenna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_est', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasenna', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('pais', models.CharField(blank=True, max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('interes', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_prof', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('contrasenna', models.CharField(max_length=30)),
                ('info_academica', models.TextField(blank=True)),
                ('info_profesional', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('interes', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_eva', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_ins', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.profesor'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.estudiante')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.profesor')),
            ],
        ),
    ]
