# Generated by Django 5.1.4 on 2025-01-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['-id'], 'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
