# Generated by Django 5.1.4 on 2025-01-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_perfil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.CharField(max_length=60),
        ),
    ]
